export function getStocks() {
  const stocks = [
    {
      logoUrl: "imgs/apple logo.jpg",
      name: "Apple Inc.",
      ticker: "APPL",
      price: (Math.random() * 200).toFixed(2),
      currency: "USD",
      change_percent:
        Math.ceil(Math.random() * 99) * (Math.round(Math.random()) ? 1 : -1),
      change_price: Math.ceil(Math.random() * 99) * (Math.round(Math.random()) ? 1 : -1),
    },
    {
      logoUrl: "imgs/nvidia logo.jpg",
      name: "NVIDIA Corporation",
      ticker: "NVDA",
      price: 180.34,
      currency: "USD",
      change_percent: -2.84,
      change_price: -5.27,
    },
    {
      logoUrl: "imgs/vanguard-logo.jpg",
      name: "Vanguard Company",
      ticker: "VOO",
      price: 542.1,
      currency: "USD",
      change_percent: 0.0,
      change_price: 0.0,
    },
    {
      logoUrl: "imgs/microsoft logo.jpg",
      name: "Microsoft Corp.",
      ticker: "MSFT",
      price: 415.5,
      currency: "USD",
      change_percent: 0.85,
      change_price: 3.52,
    },
    {
      logoUrl: "imgs/tesla logo.jpg",
      name: "Tesla Inc.",
      ticker: "TSLA",
      price: 175.22,
      currency: "USD",
      change_percent: -1.45,
      change_price: -2.58,
    },
    {
      logoUrl: "imgs/amazon logo.jpg",
      name: "Amazon.com Inc.",
      ticker: "AMZN",
      price: 189.05,
      currency: "USD",
      change_percent: 2.1,
      change_price: 3.88,
    },
    {
      logoUrl: "imgs/google logo.jpg",
      name: "Alphabet Inc.",
      ticker: "GOOGL",
      price: 175.43,
      currency: "USD",
      change_percent: 1.25,
      change_price: 2.16,
    },
    {
      logoUrl: "imgs/meta logo.jpg",
      name: "Meta Platforms Inc.",
      ticker: "META",
      price: 485.58,
      currency: "USD",
      change_percent: -0.45,
      change_price: -2.2,
    },
    {
      logoUrl: "imgs/netflix logo.jpg",
      name: "Netflix Inc.",
      ticker: "NFLX",
      price: 630.12,
      currency: "USD",
      change_percent: 3.12,
      change_price: 19.05,
    },
  ];

  return stocks;
}
